start_date: 2_days_ago
end_date: yesterday
syntax: dsl # sql|dsl
paginator: scroll # scroll|point_in_time #
index: [movies]
data_field: _source
keep_alive: 5
timeout: 60
batched_reduce_size: 20
min_score: 1
size: 10000
sort:
  year:
    order: asc
query:
  match_all: {}
